load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "pfb-demo_lib",
    srcs = ["main.go"],
    importpath = "housegate/housegate/tools/da-mvp/cmd/pfb-demo",
    visibility = ["//visibility:private"],
    deps = ["//tools/da-mvp/pkg/celestia"],
)

go_binary(
    name = "pfb-demo",
    embed = [":pfb-demo_lib"],
    visibility = ["//visibility:public"],
)
