load("@rules_go//go:def.bzl", "go_library", "go_test")

go_test(
    name = "ffifetch_test",
    srcs = ["ffifetch_test.go"],
    embed = [":ffifetch"],
)

go_library(
    name = "ffifetch",
    srcs = ["ffifetch.go"],
    importpath = "github.com/housegate/housegate/pkg/ffifetch",
    visibility = ["//visibility:public"],
    deps = ["//pkg/log"],
)
