package concurrency

// redislimiter.go — Redis + Lua concurrency limiter, generic dimension model.
//
// Adapted from sentio-core/common/requestlimiter. The original tracks four
// hardcoded dimensions (user / project / IP / tier); this port generalises
// to N dimensions passed per-call. Adding a new dimension is one
// resolver-fn change in the Plugin; the limiter and Lua scripts stay put.
//
// Storage model is unchanged: one Redis sorted set per (dimension, value),
// member = limiterID, score = acquire timestamp. ZREMRANGEBYSCORE on every
// Acquire reaps slots from processes that crashed without releasing.

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync/atomic"
	"time"

	"housegate/housegate/pkg/log"

	"github.com/redis/go-redis/v9"
)

// Sentinel errors returned by Acquire and used by Plugin to decide
// fail-open vs reject behaviour.
var (
	// ErrQuotaExceeded means at least one dimension was at its cap. The
	// wrapped message identifies which dimension and the current/limit
	// counts. Always surfaced to the client as a query rejection.
	ErrQuotaExceeded = errors.New("concurrency quota exceeded")

	// ErrAcquireFailed means the limiter could not produce a verdict
	// (Redis unreachable, Lua error, malformed reply). Plugin's FailOpen
	// flag decides whether to allow the query through.
	ErrAcquireFailed = errors.New("concurrency limiter acquire failed")
)

// Dimension describes one counting bucket for an Acquire call.
//
// Name namespaces the Redis key and appears in rejection messages; it
// should be stable per dimension (e.g. "user", "stake_level"). Value is
// the identity within the dimension (e.g. an Ethereum address). Quota is
// the per-(dimension, value) concurrency cap; <= 0 means "track but do
// not enforce" — useful for adding a dimension to observability before
// turning on enforcement.
//
// Callers MUST filter out dimensions with empty Value before calling
// Acquire — the limiter assumes every supplied Dimension has a non-empty
// Value.
type Dimension struct {
	Name  string
	Value string
	Quota int
}

// Permit is the opaque handle returned by Acquire. Hold it across the
// life of the protected operation and pass it back to Release. The keys
// field is private because callers must not invent or mutate it.
type Permit struct {
	ID   string
	keys []string
}

// IsZero reports whether p was returned by an Acquire that did no work
// (typically because the dim list was empty). Release on a zero Permit
// is a no-op; this method exists so callers can short-circuit too.
func (p Permit) IsZero() bool { return p.ID == "" && len(p.keys) == 0 }

// Limiter is the abstraction the Plugin depends on. The Redis-backed
// implementation lives below; tests substitute a fake.
type Limiter interface {
	// Acquire takes a permit across every dimension in dims atomically.
	// On success returns a non-zero Permit. On quota rejection by any
	// dimension returns ErrQuotaExceeded (wrapped, with dimension name
	// and current/limit detail). On infrastructure failure returns
	// ErrAcquireFailed (wrapped). Acquire on an empty dims slice is a
	// no-op success returning the zero Permit.
	Acquire(ctx context.Context, dims []Dimension) (Permit, error)

	// Release removes the permit from every dimension key it was added
	// to. Logs and swallows Redis errors — the limiter timeout reaps
	// stale entries. Release on a zero Permit is a no-op.
	Release(ctx context.Context, p Permit)
}

// keyPrefix namespaces our Redis keys: housegate:concurrency:<dim>:<value>.
const keyPrefix = "housegate:concurrency:"

func keyOf(dimName, value string) string {
	var b strings.Builder
	b.Grow(len(keyPrefix) + len(dimName) + 1 + len(value))
	b.WriteString(keyPrefix)
	b.WriteString(dimName)
	b.WriteByte(':')
	b.WriteString(value)
	return b.String()
}

// acquireScript is a variadic-key port of sentio-core's acquire.lua.
//
//	KEYS    = one Redis key per dimension
//	ARGV[1] = current timestamp (seconds since epoch)
//	ARGV[2] = expired timestamp (acquires before this score are reaped)
//	ARGV[3] = limiter_id (opaque, generated by caller)
//	ARGV[4..3+N]            = quotas per dimension (0 disables)
//	ARGV[4+N..3+2N]         = dimension names per dimension (for error)
//
// Reply is "ok" on success or "quota:<name>:<current>/<limit>" on
// rejection. Anything else is treated as an infrastructure error by the
// Go caller.
var acquireScript = redis.NewScript(`
local now = tonumber(ARGV[1])
local expired = tonumber(ARGV[2])
local id = ARGV[3]
local n = #KEYS

for i = 1, n do
  redis.call('ZREMRANGEBYSCORE', KEYS[i], '-inf', expired)
end

for i = 1, n do
  local quota = tonumber(ARGV[3 + i])
  if quota > 0 then
    local current = redis.call('ZCARD', KEYS[i])
    if current >= quota then
      local name = ARGV[3 + n + i]
      return 'quota:' .. name .. ':' .. tostring(current) .. '/' .. tostring(quota)
    end
  end
end

for i = 1, n do
  redis.call('ZADD', KEYS[i], now, id)
end
return 'ok'
`)

// releaseScript removes a permit ID from every supplied key.
//
//	KEYS    = the keys recorded on the Permit
//	ARGV[1] = limiter_id
var releaseScript = redis.NewScript(`
local id = ARGV[1]
for i = 1, #KEYS do
  redis.call('ZREM', KEYS[i], id)
end
return 'ok'
`)

// redisLimiter is the production implementation: a Redis client, a
// stale-permit reap window, and a process-scoped ID counter.
type redisLimiter struct {
	client  *redis.Client
	timeout time.Duration

	counter atomic.Uint64
	pid     int
}

// NewRedisLimiter constructs a Limiter backed by client. timeout is the
// stale-permit reap window — a permit older than this is treated as
// abandoned the next time anyone acquires under the same dimension.
//
// Quotas are not constructor parameters because they are per-dimension
// and per-call (set on each Dimension passed to Acquire). This lets
// dynamic policies (e.g. quota varies with stake level) live in the
// resolver that produced the Dimension rather than in the limiter.
func NewRedisLimiter(client *redis.Client, timeout time.Duration) Limiter {
	return &redisLimiter{
		client:  client,
		timeout: timeout,
		pid:     os.Getpid(),
	}
}

// generateID produces an opaque limiterID unique within this process.
// Callers never inspect it; Redis stores it as a sorted-set member.
func (l *redisLimiter) generateID() string {
	var b strings.Builder
	b.Grow(48)
	b.WriteString(strconv.FormatInt(time.Now().UnixNano(), 10))
	b.WriteByte(':')
	b.WriteString(strconv.Itoa(l.pid))
	b.WriteByte(':')
	b.WriteString(strconv.FormatUint(l.counter.Add(1), 10))
	return b.String()
}

func (l *redisLimiter) Acquire(ctx context.Context, dims []Dimension) (Permit, error) {
	if len(dims) == 0 {
		return Permit{}, nil
	}
	id := l.generateID()
	now := time.Now().Unix()
	expired := now - int64(l.timeout.Seconds())

	keys := make([]string, len(dims))
	// argv layout: now, expired, id, quota_1..quota_N, name_1..name_N
	argv := make([]any, 0, 3+2*len(dims))
	argv = append(argv, now, expired, id)
	for i, d := range dims {
		keys[i] = keyOf(d.Name, d.Value)
		argv = append(argv, d.Quota)
	}
	for _, d := range dims {
		argv = append(argv, d.Name)
	}

	res, err := acquireScript.Run(ctx, l.client, keys, argv...).Result()
	if err != nil {
		return Permit{}, fmt.Errorf("%w: %v", ErrAcquireFailed, err)
	}
	s, ok := res.(string)
	if !ok {
		return Permit{}, fmt.Errorf("%w: unexpected reply type %T", ErrAcquireFailed, res)
	}
	prefix, detail, found := strings.Cut(s, ":")
	if !found && s != "ok" {
		return Permit{}, fmt.Errorf("%w: malformed reply %q", ErrAcquireFailed, s)
	}
	switch prefix {
	case "ok":
		return Permit{ID: id, keys: keys}, nil
	case "quota":
		// detail = "<dim_name>:<current>/<limit>"
		return Permit{}, fmt.Errorf("%w: %s", ErrQuotaExceeded, detail)
	default:
		return Permit{}, fmt.Errorf("%w: unknown status %q", ErrAcquireFailed, prefix)
	}
}

func (l *redisLimiter) Release(ctx context.Context, p Permit) {
	if p.IsZero() {
		return
	}
	if _, err := releaseScript.Run(ctx, l.client, p.keys, p.ID).Result(); err != nil {
		log.Warnfe(err, "concurrency limiter: release failed limiter_id=%v keys=%v", p.ID, p.keys)
	}
}
