// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: protos/rewriter.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewriteOp int32

const (
	RewriteOp_TableNameRewrite       RewriteOp = 0
	RewriteOp_LimitRewrite           RewriteOp = 1
	RewriteOp_OffsetRewrite          RewriteOp = 2
	RewriteOp_SettingsRewrite        RewriteOp = 3
	RewriteOp_CommonTableExprRewrite RewriteOp = 4
)

// Enum value maps for RewriteOp.
var (
	RewriteOp_name = map[int32]string{
		0: "TableNameRewrite",
		1: "LimitRewrite",
		2: "OffsetRewrite",
		3: "SettingsRewrite",
		4: "CommonTableExprRewrite",
	}
	RewriteOp_value = map[string]int32{
		"TableNameRewrite":       0,
		"LimitRewrite":           1,
		"OffsetRewrite":          2,
		"SettingsRewrite":        3,
		"CommonTableExprRewrite": 4,
	}
)

func (x RewriteOp) Enum() *RewriteOp {
	p := new(RewriteOp)
	*p = x
	return p
}

func (x RewriteOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewriteOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[0].Descriptor()
}

func (RewriteOp) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[0]
}

func (x RewriteOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewriteOp.Descriptor instead.
func (RewriteOp) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0}
}

type SettingType int32

const (
	SettingType_String SettingType = 0
	SettingType_Bool   SettingType = 1
	SettingType_Int    SettingType = 2
	SettingType_Uint64 SettingType = 3
)

// Enum value maps for SettingType.
var (
	SettingType_name = map[int32]string{
		0: "String",
		1: "Bool",
		2: "Int",
		3: "Uint64",
	}
	SettingType_value = map[string]int32{
		"String": 0,
		"Bool":   1,
		"Int":    2,
		"Uint64": 3,
	}
)

func (x SettingType) Enum() *SettingType {
	p := new(SettingType)
	*p = x
	return p
}

func (x SettingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[1].Descriptor()
}

func (SettingType) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[1]
}

func (x SettingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingType.Descriptor instead.
func (SettingType) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{1}
}

type RewriteCode int32

const (
	RewriteCode_Success               RewriteCode = 0
	RewriteCode_SyntaxError           RewriteCode = 1
	RewriteCode_RewriteError          RewriteCode = 2
	RewriteCode_UnsupportedStatement  RewriteCode = 3
	RewriteCode_InvalidRewriteRequest RewriteCode = 4
)

// Enum value maps for RewriteCode.
var (
	RewriteCode_name = map[int32]string{
		0: "Success",
		1: "SyntaxError",
		2: "RewriteError",
		3: "UnsupportedStatement",
		4: "InvalidRewriteRequest",
	}
	RewriteCode_value = map[string]int32{
		"Success":               0,
		"SyntaxError":           1,
		"RewriteError":          2,
		"UnsupportedStatement":  3,
		"InvalidRewriteRequest": 4,
	}
)

func (x RewriteCode) Enum() *RewriteCode {
	p := new(RewriteCode)
	*p = x
	return p
}

func (x RewriteCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewriteCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[2].Descriptor()
}

func (RewriteCode) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[2]
}

func (x RewriteCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewriteCode.Descriptor instead.
func (RewriteCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{2}
}

type StatementType int32

const (
	StatementType_STATEMENT_TYPE_UNSPECIFIED       StatementType = 0
	StatementType_STATEMENT_TYPE_SELECT            StatementType = 1
	StatementType_STATEMENT_TYPE_USE               StatementType = 2
	StatementType_STATEMENT_TYPE_SHOW_TABLES       StatementType = 3
	StatementType_STATEMENT_TYPE_SHOW_CREATE_TABLE StatementType = 4
	StatementType_STATEMENT_TYPE_EXISTS_TABLE      StatementType = 5
	StatementType_STATEMENT_TYPE_CREATE_TABLE      StatementType = 6
	StatementType_STATEMENT_TYPE_DROP_TABLE        StatementType = 7
	StatementType_STATEMENT_TYPE_ALTER_TABLE       StatementType = 8
	StatementType_STATEMENT_TYPE_RENAME_TABLE      StatementType = 9
	StatementType_STATEMENT_TYPE_INSERT            StatementType = 10
	StatementType_STATEMENT_TYPE_UPDATE            StatementType = 11
	StatementType_STATEMENT_TYPE_DELETE            StatementType = 12
	StatementType_STATEMENT_TYPE_CREATE_DATABASE   StatementType = 13
	StatementType_STATEMENT_TYPE_SHOW_DATABASES    StatementType = 14
	StatementType_STATEMENT_TYPE_DROP_DATABASE     StatementType = 15
	StatementType_STATEMENT_TYPE_TRUNCATE_TABLE    StatementType = 16
	StatementType_STATEMENT_TYPE_GRANT             StatementType = 17
	StatementType_STATEMENT_TYPE_REVOKE            StatementType = 18
)

// Enum value maps for StatementType.
var (
	StatementType_name = map[int32]string{
		0:  "STATEMENT_TYPE_UNSPECIFIED",
		1:  "STATEMENT_TYPE_SELECT",
		2:  "STATEMENT_TYPE_USE",
		3:  "STATEMENT_TYPE_SHOW_TABLES",
		4:  "STATEMENT_TYPE_SHOW_CREATE_TABLE",
		5:  "STATEMENT_TYPE_EXISTS_TABLE",
		6:  "STATEMENT_TYPE_CREATE_TABLE",
		7:  "STATEMENT_TYPE_DROP_TABLE",
		8:  "STATEMENT_TYPE_ALTER_TABLE",
		9:  "STATEMENT_TYPE_RENAME_TABLE",
		10: "STATEMENT_TYPE_INSERT",
		11: "STATEMENT_TYPE_UPDATE",
		12: "STATEMENT_TYPE_DELETE",
		13: "STATEMENT_TYPE_CREATE_DATABASE",
		14: "STATEMENT_TYPE_SHOW_DATABASES",
		15: "STATEMENT_TYPE_DROP_DATABASE",
		16: "STATEMENT_TYPE_TRUNCATE_TABLE",
		17: "STATEMENT_TYPE_GRANT",
		18: "STATEMENT_TYPE_REVOKE",
	}
	StatementType_value = map[string]int32{
		"STATEMENT_TYPE_UNSPECIFIED":       0,
		"STATEMENT_TYPE_SELECT":            1,
		"STATEMENT_TYPE_USE":               2,
		"STATEMENT_TYPE_SHOW_TABLES":       3,
		"STATEMENT_TYPE_SHOW_CREATE_TABLE": 4,
		"STATEMENT_TYPE_EXISTS_TABLE":      5,
		"STATEMENT_TYPE_CREATE_TABLE":      6,
		"STATEMENT_TYPE_DROP_TABLE":        7,
		"STATEMENT_TYPE_ALTER_TABLE":       8,
		"STATEMENT_TYPE_RENAME_TABLE":      9,
		"STATEMENT_TYPE_INSERT":            10,
		"STATEMENT_TYPE_UPDATE":            11,
		"STATEMENT_TYPE_DELETE":            12,
		"STATEMENT_TYPE_CREATE_DATABASE":   13,
		"STATEMENT_TYPE_SHOW_DATABASES":    14,
		"STATEMENT_TYPE_DROP_DATABASE":     15,
		"STATEMENT_TYPE_TRUNCATE_TABLE":    16,
		"STATEMENT_TYPE_GRANT":             17,
		"STATEMENT_TYPE_REVOKE":            18,
	}
)

func (x StatementType) Enum() *StatementType {
	p := new(StatementType)
	*p = x
	return p
}

func (x StatementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[3].Descriptor()
}

func (StatementType) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[3]
}

func (x StatementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementType.Descriptor instead.
func (StatementType) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3}
}

type PrivilegeDelta_Action int32

const (
	PrivilegeDelta_ACTION_UNSPECIFIED PrivilegeDelta_Action = 0
	PrivilegeDelta_ACTION_GRANT       PrivilegeDelta_Action = 1
	PrivilegeDelta_ACTION_REVOKE      PrivilegeDelta_Action = 2
)

// Enum value maps for PrivilegeDelta_Action.
var (
	PrivilegeDelta_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_GRANT",
		2: "ACTION_REVOKE",
	}
	PrivilegeDelta_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_GRANT":       1,
		"ACTION_REVOKE":      2,
	}
)

func (x PrivilegeDelta_Action) Enum() *PrivilegeDelta_Action {
	p := new(PrivilegeDelta_Action)
	*p = x
	return p
}

func (x PrivilegeDelta_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivilegeDelta_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[4].Descriptor()
}

func (PrivilegeDelta_Action) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[4]
}

func (x PrivilegeDelta_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivilegeDelta_Action.Descriptor instead.
func (PrivilegeDelta_Action) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{11, 0}
}

type PrivilegeDelta_Scope int32

const (
	PrivilegeDelta_SCOPE_UNSPECIFIED PrivilegeDelta_Scope = 0
	PrivilegeDelta_SCOPE_TABLE       PrivilegeDelta_Scope = 1
	PrivilegeDelta_SCOPE_DATABASE    PrivilegeDelta_Scope = 2
)

// Enum value maps for PrivilegeDelta_Scope.
var (
	PrivilegeDelta_Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_TABLE",
		2: "SCOPE_DATABASE",
	}
	PrivilegeDelta_Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_TABLE":       1,
		"SCOPE_DATABASE":    2,
	}
)

func (x PrivilegeDelta_Scope) Enum() *PrivilegeDelta_Scope {
	p := new(PrivilegeDelta_Scope)
	*p = x
	return p
}

func (x PrivilegeDelta_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivilegeDelta_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[5].Descriptor()
}

func (PrivilegeDelta_Scope) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[5]
}

func (x PrivilegeDelta_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivilegeDelta_Scope.Descriptor instead.
func (PrivilegeDelta_Scope) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{11, 1}
}

type RewriteLimitArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteLimitArgs_ReplaceLimit_
	//	*RewriteLimitArgs_ForceLimit
	Value         isRewriteLimitArgs_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteLimitArgs) Reset() {
	*x = RewriteLimitArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteLimitArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteLimitArgs) ProtoMessage() {}

func (x *RewriteLimitArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteLimitArgs.ProtoReflect.Descriptor instead.
func (*RewriteLimitArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0}
}

func (x *RewriteLimitArgs) GetValue() isRewriteLimitArgs_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteLimitArgs) GetReplaceLimit() *RewriteLimitArgs_ReplaceLimit {
	if x != nil {
		if x, ok := x.Value.(*RewriteLimitArgs_ReplaceLimit_); ok {
			return x.ReplaceLimit
		}
	}
	return nil
}

func (x *RewriteLimitArgs) GetForceLimit() int32 {
	if x != nil {
		if x, ok := x.Value.(*RewriteLimitArgs_ForceLimit); ok {
			return x.ForceLimit
		}
	}
	return 0
}

type isRewriteLimitArgs_Value interface {
	isRewriteLimitArgs_Value()
}

type RewriteLimitArgs_ReplaceLimit_ struct {
	ReplaceLimit *RewriteLimitArgs_ReplaceLimit `protobuf:"bytes,2,opt,name=replace_limit,json=replaceLimit,proto3,oneof"`
}

type RewriteLimitArgs_ForceLimit struct {
	ForceLimit int32 `protobuf:"varint,3,opt,name=force_limit,json=forceLimit,proto3,oneof"`
}

func (*RewriteLimitArgs_ReplaceLimit_) isRewriteLimitArgs_Value() {}

func (*RewriteLimitArgs_ForceLimit) isRewriteLimitArgs_Value() {}

type RewriteOffsetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteOffsetArgs) Reset() {
	*x = RewriteOffsetArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteOffsetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteOffsetArgs) ProtoMessage() {}

func (x *RewriteOffsetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteOffsetArgs.ProtoReflect.Descriptor instead.
func (*RewriteOffsetArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{1}
}

func (x *RewriteOffsetArgs) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RewriteCommonTableExprArgs struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	CteMap        map[string]*RewriteCommonTableExprArgs_CommonTableExpr `protobuf:"bytes,1,rep,name=cte_map,json=cteMap,proto3" json:"cte_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteCommonTableExprArgs) Reset() {
	*x = RewriteCommonTableExprArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteCommonTableExprArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteCommonTableExprArgs) ProtoMessage() {}

func (x *RewriteCommonTableExprArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteCommonTableExprArgs.ProtoReflect.Descriptor instead.
func (*RewriteCommonTableExprArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{2}
}

func (x *RewriteCommonTableExprArgs) GetCteMap() map[string]*RewriteCommonTableExprArgs_CommonTableExpr {
	if x != nil {
		return x.CteMap
	}
	return nil
}

type RewriteTableStaticArgs struct {
	state                protoimpl.MessageState                               `protogen:"open.v1"`
	TableMap             map[string]string                                    `protobuf:"bytes,1,rep,name=table_map,json=tableMap,proto3" json:"table_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoteTableMap       map[string]*RewriteTableStaticArgs_RemoteTable       `protobuf:"bytes,2,rep,name=remote_table_map,json=remoteTableMap,proto3" json:"remote_table_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TableWithDatabaseMap map[string]*RewriteTableStaticArgs_TableWithDatabase `protobuf:"bytes,3,rep,name=table_with_database_map,json=tableWithDatabaseMap,proto3" json:"table_with_database_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RewriteTableStaticArgs) Reset() {
	*x = RewriteTableStaticArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableStaticArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableStaticArgs) ProtoMessage() {}

func (x *RewriteTableStaticArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableStaticArgs.ProtoReflect.Descriptor instead.
func (*RewriteTableStaticArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3}
}

func (x *RewriteTableStaticArgs) GetTableMap() map[string]string {
	if x != nil {
		return x.TableMap
	}
	return nil
}

func (x *RewriteTableStaticArgs) GetRemoteTableMap() map[string]*RewriteTableStaticArgs_RemoteTable {
	if x != nil {
		return x.RemoteTableMap
	}
	return nil
}

func (x *RewriteTableStaticArgs) GetTableWithDatabaseMap() map[string]*RewriteTableStaticArgs_TableWithDatabase {
	if x != nil {
		return x.TableWithDatabaseMap
	}
	return nil
}

type RewriteTableDynamicArgs struct {
	state                                protoimpl.MessageState                             `protogen:"open.v1"`
	DatabaseMap                          map[string]string                                  `protobuf:"bytes,1,rep,name=database_map,json=databaseMap,proto3" json:"database_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	KnownPhysicalDatabases               []string                                           `protobuf:"bytes,2,rep,name=known_physical_databases,json=knownPhysicalDatabases,proto3" json:"known_physical_databases,omitempty"`
	UpstreamLogicalDatabaseInContext     string                                             `protobuf:"bytes,3,opt,name=upstream_logical_database_in_context,json=upstreamLogicalDatabaseInContext,proto3" json:"upstream_logical_database_in_context,omitempty"`
	Delim                                string                                             `protobuf:"bytes,4,opt,name=delim,proto3" json:"delim,omitempty"`
	ExtraArguments                       []string                                           `protobuf:"bytes,5,rep,name=extra_arguments,json=extraArguments,proto3" json:"extra_arguments,omitempty"`
	UpstreamPhysicalDatabaseInContext    *string                                            `protobuf:"bytes,6,opt,name=upstream_physical_database_in_context,json=upstreamPhysicalDatabaseInContext,proto3,oneof" json:"upstream_physical_database_in_context,omitempty"`
	LogicalDatabaseToRemoteUpstreamIndex map[string]string                                  `protobuf:"bytes,7,rep,name=logical_database_to_remote_upstream_index,json=logicalDatabaseToRemoteUpstreamIndex,proto3" json:"logical_database_to_remote_upstream_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoteUpstreams                      map[string]*RewriteTableDynamicArgs_RemoteUpstream `protobuf:"bytes,8,rep,name=remote_upstreams,json=remoteUpstreams,proto3" json:"remote_upstreams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *RewriteTableDynamicArgs) Reset() {
	*x = RewriteTableDynamicArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableDynamicArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableDynamicArgs) ProtoMessage() {}

func (x *RewriteTableDynamicArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableDynamicArgs.ProtoReflect.Descriptor instead.
func (*RewriteTableDynamicArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{4}
}

func (x *RewriteTableDynamicArgs) GetDatabaseMap() map[string]string {
	if x != nil {
		return x.DatabaseMap
	}
	return nil
}

func (x *RewriteTableDynamicArgs) GetKnownPhysicalDatabases() []string {
	if x != nil {
		return x.KnownPhysicalDatabases
	}
	return nil
}

func (x *RewriteTableDynamicArgs) GetUpstreamLogicalDatabaseInContext() string {
	if x != nil {
		return x.UpstreamLogicalDatabaseInContext
	}
	return ""
}

func (x *RewriteTableDynamicArgs) GetDelim() string {
	if x != nil {
		return x.Delim
	}
	return ""
}

func (x *RewriteTableDynamicArgs) GetExtraArguments() []string {
	if x != nil {
		return x.ExtraArguments
	}
	return nil
}

func (x *RewriteTableDynamicArgs) GetUpstreamPhysicalDatabaseInContext() string {
	if x != nil && x.UpstreamPhysicalDatabaseInContext != nil {
		return *x.UpstreamPhysicalDatabaseInContext
	}
	return ""
}

func (x *RewriteTableDynamicArgs) GetLogicalDatabaseToRemoteUpstreamIndex() map[string]string {
	if x != nil {
		return x.LogicalDatabaseToRemoteUpstreamIndex
	}
	return nil
}

func (x *RewriteTableDynamicArgs) GetRemoteUpstreams() map[string]*RewriteTableDynamicArgs_RemoteUpstream {
	if x != nil {
		return x.RemoteUpstreams
	}
	return nil
}

type RewriteTableNameArgs struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DynamicArgs   *RewriteTableDynamicArgs `protobuf:"bytes,1,opt,name=dynamic_args,json=dynamicArgs,proto3" json:"dynamic_args,omitempty"`
	StaticArgs    *RewriteTableStaticArgs  `protobuf:"bytes,2,opt,name=static_args,json=staticArgs,proto3,oneof" json:"static_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableNameArgs) Reset() {
	*x = RewriteTableNameArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableNameArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableNameArgs) ProtoMessage() {}

func (x *RewriteTableNameArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableNameArgs.ProtoReflect.Descriptor instead.
func (*RewriteTableNameArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{5}
}

func (x *RewriteTableNameArgs) GetDynamicArgs() *RewriteTableDynamicArgs {
	if x != nil {
		return x.DynamicArgs
	}
	return nil
}

func (x *RewriteTableNameArgs) GetStaticArgs() *RewriteTableStaticArgs {
	if x != nil {
		return x.StaticArgs
	}
	return nil
}

type RewriteSettingsArgs struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Settings      []*RewriteSettingsArgs_Setting `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSettingsArgs) Reset() {
	*x = RewriteSettingsArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSettingsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSettingsArgs) ProtoMessage() {}

func (x *RewriteSettingsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSettingsArgs.ProtoReflect.Descriptor instead.
func (*RewriteSettingsArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{6}
}

func (x *RewriteSettingsArgs) GetSettings() []*RewriteSettingsArgs_Setting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type RewriteOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    RewriteOp              `protobuf:"varint,1,opt,name=op,proto3,enum=rewriter.RewriteOp" json:"op,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteOption_TableNameArgs
	//	*RewriteOption_LimitArgs
	//	*RewriteOption_OffsetArgs
	//	*RewriteOption_SettingsArgs
	//	*RewriteOption_CommonTableExprArgs
	Value         isRewriteOption_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteOption) Reset() {
	*x = RewriteOption{}
	mi := &file_protos_rewriter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteOption) ProtoMessage() {}

func (x *RewriteOption) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteOption.ProtoReflect.Descriptor instead.
func (*RewriteOption) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{7}
}

func (x *RewriteOption) GetOp() RewriteOp {
	if x != nil {
		return x.Op
	}
	return RewriteOp_TableNameRewrite
}

func (x *RewriteOption) GetValue() isRewriteOption_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteOption) GetTableNameArgs() *RewriteTableNameArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_TableNameArgs); ok {
			return x.TableNameArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetLimitArgs() *RewriteLimitArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_LimitArgs); ok {
			return x.LimitArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetOffsetArgs() *RewriteOffsetArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_OffsetArgs); ok {
			return x.OffsetArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetSettingsArgs() *RewriteSettingsArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_SettingsArgs); ok {
			return x.SettingsArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetCommonTableExprArgs() *RewriteCommonTableExprArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_CommonTableExprArgs); ok {
			return x.CommonTableExprArgs
		}
	}
	return nil
}

type isRewriteOption_Value interface {
	isRewriteOption_Value()
}

type RewriteOption_TableNameArgs struct {
	TableNameArgs *RewriteTableNameArgs `protobuf:"bytes,2,opt,name=table_name_args,json=tableNameArgs,proto3,oneof"`
}

type RewriteOption_LimitArgs struct {
	LimitArgs *RewriteLimitArgs `protobuf:"bytes,3,opt,name=limit_args,json=limitArgs,proto3,oneof"`
}

type RewriteOption_OffsetArgs struct {
	OffsetArgs *RewriteOffsetArgs `protobuf:"bytes,4,opt,name=offset_args,json=offsetArgs,proto3,oneof"`
}

type RewriteOption_SettingsArgs struct {
	SettingsArgs *RewriteSettingsArgs `protobuf:"bytes,5,opt,name=settings_args,json=settingsArgs,proto3,oneof"`
}

type RewriteOption_CommonTableExprArgs struct {
	CommonTableExprArgs *RewriteCommonTableExprArgs `protobuf:"bytes,6,opt,name=common_table_expr_args,json=commonTableExprArgs,proto3,oneof"`
}

func (*RewriteOption_TableNameArgs) isRewriteOption_Value() {}

func (*RewriteOption_LimitArgs) isRewriteOption_Value() {}

func (*RewriteOption_OffsetArgs) isRewriteOption_Value() {}

func (*RewriteOption_SettingsArgs) isRewriteOption_Value() {}

func (*RewriteOption_CommonTableExprArgs) isRewriteOption_Value() {}

type RewriteSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Options       []*RewriteOption       `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSQLRequest) Reset() {
	*x = RewriteSQLRequest{}
	mi := &file_protos_rewriter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSQLRequest) ProtoMessage() {}

func (x *RewriteSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSQLRequest.ProtoReflect.Descriptor instead.
func (*RewriteSQLRequest) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{8}
}

func (x *RewriteSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *RewriteSQLRequest) GetOptions() []*RewriteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type RewriteSQLResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Code                   RewriteCode            `protobuf:"varint,1,opt,name=code,proto3,enum=rewriter.RewriteCode" json:"code,omitempty"`
	Message                string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SqlAfterRewrite        string                 `protobuf:"bytes,3,opt,name=sql_after_rewrite,json=sqlAfterRewrite,proto3" json:"sql_after_rewrite,omitempty"`
	StatementType          StatementType          `protobuf:"varint,5,opt,name=statement_type,json=statementType,proto3,enum=rewriter.StatementType" json:"statement_type,omitempty"`
	FailedCteAliases       []string               `protobuf:"bytes,9,rep,name=failed_cte_aliases,json=failedCteAliases,proto3" json:"failed_cte_aliases,omitempty"`
	TableRewrites          map[string]string      `protobuf:"bytes,10,rep,name=table_rewrites,json=tableRewrites,proto3" json:"table_rewrites,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DatabaseRewrites       map[string]string      `protobuf:"bytes,11,rep,name=database_rewrites,json=databaseRewrites,proto3" json:"database_rewrites,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OriginalAccessedTables []*AccessedTable       `protobuf:"bytes,12,rep,name=original_accessed_tables,json=originalAccessedTables,proto3" json:"original_accessed_tables,omitempty"`
	PrivilegesDeltas       []*PrivilegeDelta      `protobuf:"bytes,13,rep,name=privileges_deltas,json=privilegesDeltas,proto3" json:"privileges_deltas,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RewriteSQLResponse) Reset() {
	*x = RewriteSQLResponse{}
	mi := &file_protos_rewriter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSQLResponse) ProtoMessage() {}

func (x *RewriteSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSQLResponse.ProtoReflect.Descriptor instead.
func (*RewriteSQLResponse) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{9}
}

func (x *RewriteSQLResponse) GetCode() RewriteCode {
	if x != nil {
		return x.Code
	}
	return RewriteCode_Success
}

func (x *RewriteSQLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RewriteSQLResponse) GetSqlAfterRewrite() string {
	if x != nil {
		return x.SqlAfterRewrite
	}
	return ""
}

func (x *RewriteSQLResponse) GetStatementType() StatementType {
	if x != nil {
		return x.StatementType
	}
	return StatementType_STATEMENT_TYPE_UNSPECIFIED
}

func (x *RewriteSQLResponse) GetFailedCteAliases() []string {
	if x != nil {
		return x.FailedCteAliases
	}
	return nil
}

func (x *RewriteSQLResponse) GetTableRewrites() map[string]string {
	if x != nil {
		return x.TableRewrites
	}
	return nil
}

func (x *RewriteSQLResponse) GetDatabaseRewrites() map[string]string {
	if x != nil {
		return x.DatabaseRewrites
	}
	return nil
}

func (x *RewriteSQLResponse) GetOriginalAccessedTables() []*AccessedTable {
	if x != nil {
		return x.OriginalAccessedTables
	}
	return nil
}

func (x *RewriteSQLResponse) GetPrivilegesDeltas() []*PrivilegeDelta {
	if x != nil {
		return x.PrivilegesDeltas
	}
	return nil
}

type AccessedTable struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginalDatabase string                 `protobuf:"bytes,1,opt,name=original_database,json=originalDatabase,proto3" json:"original_database,omitempty"`
	OriginalTable    string                 `protobuf:"bytes,2,opt,name=original_table,json=originalTable,proto3" json:"original_table,omitempty"`
	LogicalDatabase  string                 `protobuf:"bytes,3,opt,name=logical_database,json=logicalDatabase,proto3" json:"logical_database,omitempty"`
	PhysicalDatabase string                 `protobuf:"bytes,4,opt,name=physical_database,json=physicalDatabase,proto3" json:"physical_database,omitempty"`
	IsRemote         bool                   `protobuf:"varint,5,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessedTable) Reset() {
	*x = AccessedTable{}
	mi := &file_protos_rewriter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessedTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessedTable) ProtoMessage() {}

func (x *AccessedTable) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessedTable.ProtoReflect.Descriptor instead.
func (*AccessedTable) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{10}
}

func (x *AccessedTable) GetOriginalDatabase() string {
	if x != nil {
		return x.OriginalDatabase
	}
	return ""
}

func (x *AccessedTable) GetOriginalTable() string {
	if x != nil {
		return x.OriginalTable
	}
	return ""
}

func (x *AccessedTable) GetLogicalDatabase() string {
	if x != nil {
		return x.LogicalDatabase
	}
	return ""
}

func (x *AccessedTable) GetPhysicalDatabase() string {
	if x != nil {
		return x.PhysicalDatabase
	}
	return ""
}

func (x *AccessedTable) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

type PrivilegeDelta struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Action           PrivilegeDelta_Action     `protobuf:"varint,1,opt,name=action,proto3,enum=rewriter.PrivilegeDelta_Action" json:"action,omitempty"`
	Scope            PrivilegeDelta_Scope      `protobuf:"varint,2,opt,name=scope,proto3,enum=rewriter.PrivilegeDelta_Scope" json:"scope,omitempty"`
	OriginalDatabase string                    `protobuf:"bytes,3,opt,name=original_database,json=originalDatabase,proto3" json:"original_database,omitempty"`
	LogicalDatabase  string                    `protobuf:"bytes,4,opt,name=logical_database,json=logicalDatabase,proto3" json:"logical_database,omitempty"`
	PhysicalDatabase string                    `protobuf:"bytes,5,opt,name=physical_database,json=physicalDatabase,proto3" json:"physical_database,omitempty"`
	OriginalTable    string                    `protobuf:"bytes,6,opt,name=original_table,json=originalTable,proto3" json:"original_table,omitempty"`
	PhysicalTable    string                    `protobuf:"bytes,7,opt,name=physical_table,json=physicalTable,proto3" json:"physical_table,omitempty"`
	Privileges       []string                  `protobuf:"bytes,8,rep,name=privileges,proto3" json:"privileges,omitempty"`
	Grantees         []*PrivilegeDelta_Grantee `protobuf:"bytes,9,rep,name=grantees,proto3" json:"grantees,omitempty"`
	GrantOption      bool                      `protobuf:"varint,10,opt,name=grant_option,json=grantOption,proto3" json:"grant_option,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrivilegeDelta) Reset() {
	*x = PrivilegeDelta{}
	mi := &file_protos_rewriter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeDelta) ProtoMessage() {}

func (x *PrivilegeDelta) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeDelta.ProtoReflect.Descriptor instead.
func (*PrivilegeDelta) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{11}
}

func (x *PrivilegeDelta) GetAction() PrivilegeDelta_Action {
	if x != nil {
		return x.Action
	}
	return PrivilegeDelta_ACTION_UNSPECIFIED
}

func (x *PrivilegeDelta) GetScope() PrivilegeDelta_Scope {
	if x != nil {
		return x.Scope
	}
	return PrivilegeDelta_SCOPE_UNSPECIFIED
}

func (x *PrivilegeDelta) GetOriginalDatabase() string {
	if x != nil {
		return x.OriginalDatabase
	}
	return ""
}

func (x *PrivilegeDelta) GetLogicalDatabase() string {
	if x != nil {
		return x.LogicalDatabase
	}
	return ""
}

func (x *PrivilegeDelta) GetPhysicalDatabase() string {
	if x != nil {
		return x.PhysicalDatabase
	}
	return ""
}

func (x *PrivilegeDelta) GetOriginalTable() string {
	if x != nil {
		return x.OriginalTable
	}
	return ""
}

func (x *PrivilegeDelta) GetPhysicalTable() string {
	if x != nil {
		return x.PhysicalTable
	}
	return ""
}

func (x *PrivilegeDelta) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *PrivilegeDelta) GetGrantees() []*PrivilegeDelta_Grantee {
	if x != nil {
		return x.Grantees
	}
	return nil
}

func (x *PrivilegeDelta) GetGrantOption() bool {
	if x != nil {
		return x.GrantOption
	}
	return false
}

type RewriteErrorMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Options       []*RewriteOption       `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteErrorMessageRequest) Reset() {
	*x = RewriteErrorMessageRequest{}
	mi := &file_protos_rewriter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteErrorMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteErrorMessageRequest) ProtoMessage() {}

func (x *RewriteErrorMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteErrorMessageRequest.ProtoReflect.Descriptor instead.
func (*RewriteErrorMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{12}
}

func (x *RewriteErrorMessageRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *RewriteErrorMessageRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RewriteErrorMessageRequest) GetOptions() []*RewriteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type RewriteErrorMessageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              RewriteCode            `protobuf:"varint,1,opt,name=code,proto3,enum=rewriter.RewriteCode" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorAfterRewrite string                 `protobuf:"bytes,3,opt,name=error_after_rewrite,json=errorAfterRewrite,proto3" json:"error_after_rewrite,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RewriteErrorMessageResponse) Reset() {
	*x = RewriteErrorMessageResponse{}
	mi := &file_protos_rewriter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteErrorMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteErrorMessageResponse) ProtoMessage() {}

func (x *RewriteErrorMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteErrorMessageResponse.ProtoReflect.Descriptor instead.
func (*RewriteErrorMessageResponse) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{13}
}

func (x *RewriteErrorMessageResponse) GetCode() RewriteCode {
	if x != nil {
		return x.Code
	}
	return RewriteCode_Success
}

func (x *RewriteErrorMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RewriteErrorMessageResponse) GetErrorAfterRewrite() string {
	if x != nil {
		return x.ErrorAfterRewrite
	}
	return ""
}

type RewriteLimitArgs_ReplaceLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int32                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	ReplaceTo     int32                  `protobuf:"varint,2,opt,name=replace_to,json=replaceTo,proto3" json:"replace_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteLimitArgs_ReplaceLimit) Reset() {
	*x = RewriteLimitArgs_ReplaceLimit{}
	mi := &file_protos_rewriter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteLimitArgs_ReplaceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteLimitArgs_ReplaceLimit) ProtoMessage() {}

func (x *RewriteLimitArgs_ReplaceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteLimitArgs_ReplaceLimit.ProtoReflect.Descriptor instead.
func (*RewriteLimitArgs_ReplaceLimit) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RewriteLimitArgs_ReplaceLimit) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *RewriteLimitArgs_ReplaceLimit) GetReplaceTo() int32 {
	if x != nil {
		return x.ReplaceTo
	}
	return 0
}

type RewriteCommonTableExprArgs_CommonTableExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) Reset() {
	*x = RewriteCommonTableExprArgs_CommonTableExpr{}
	mi := &file_protos_rewriter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteCommonTableExprArgs_CommonTableExpr) ProtoMessage() {}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteCommonTableExprArgs_CommonTableExpr.ProtoReflect.Descriptor instead.
func (*RewriteCommonTableExprArgs_CommonTableExpr) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type RewriteTableStaticArgs_RemoteTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableStaticArgs_RemoteTable) Reset() {
	*x = RewriteTableStaticArgs_RemoteTable{}
	mi := &file_protos_rewriter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableStaticArgs_RemoteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableStaticArgs_RemoteTable) ProtoMessage() {}

func (x *RewriteTableStaticArgs_RemoteTable) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableStaticArgs_RemoteTable.ProtoReflect.Descriptor instead.
func (*RewriteTableStaticArgs_RemoteTable) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RewriteTableStaticArgs_RemoteTable) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RewriteTableStaticArgs_RemoteTable) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RewriteTableStaticArgs_RemoteTable) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RewriteTableStaticArgs_RemoteTable) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RewriteTableStaticArgs_RemoteTable) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RewriteTableStaticArgs_TableWithDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableStaticArgs_TableWithDatabase) Reset() {
	*x = RewriteTableStaticArgs_TableWithDatabase{}
	mi := &file_protos_rewriter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableStaticArgs_TableWithDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableStaticArgs_TableWithDatabase) ProtoMessage() {}

func (x *RewriteTableStaticArgs_TableWithDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableStaticArgs_TableWithDatabase.ProtoReflect.Descriptor instead.
func (*RewriteTableStaticArgs_TableWithDatabase) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RewriteTableStaticArgs_TableWithDatabase) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RewriteTableStaticArgs_TableWithDatabase) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type RewriteTableDynamicArgs_RemoteUpstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableDynamicArgs_RemoteUpstream) Reset() {
	*x = RewriteTableDynamicArgs_RemoteUpstream{}
	mi := &file_protos_rewriter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableDynamicArgs_RemoteUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableDynamicArgs_RemoteUpstream) ProtoMessage() {}

func (x *RewriteTableDynamicArgs_RemoteUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableDynamicArgs_RemoteUpstream.ProtoReflect.Descriptor instead.
func (*RewriteTableDynamicArgs_RemoteUpstream) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{4, 1}
}

func (x *RewriteTableDynamicArgs_RemoteUpstream) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RewriteTableDynamicArgs_RemoteUpstream) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RewriteTableDynamicArgs_RemoteUpstream) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RewriteSettingsArgs_Setting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type  SettingType            `protobuf:"varint,2,opt,name=type,proto3,enum=rewriter.SettingType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteSettingsArgs_Setting_StringValue
	//	*RewriteSettingsArgs_Setting_BoolValue
	//	*RewriteSettingsArgs_Setting_IntValue
	//	*RewriteSettingsArgs_Setting_Uint64Value
	Value         isRewriteSettingsArgs_Setting_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSettingsArgs_Setting) Reset() {
	*x = RewriteSettingsArgs_Setting{}
	mi := &file_protos_rewriter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSettingsArgs_Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSettingsArgs_Setting) ProtoMessage() {}

func (x *RewriteSettingsArgs_Setting) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSettingsArgs_Setting.ProtoReflect.Descriptor instead.
func (*RewriteSettingsArgs_Setting) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RewriteSettingsArgs_Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RewriteSettingsArgs_Setting) GetType() SettingType {
	if x != nil {
		return x.Type
	}
	return SettingType_String
}

func (x *RewriteSettingsArgs_Setting) GetValue() isRewriteSettingsArgs_Setting_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteSettingsArgs_Setting) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *RewriteSettingsArgs_Setting) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *RewriteSettingsArgs_Setting) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *RewriteSettingsArgs_Setting) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

type isRewriteSettingsArgs_Setting_Value interface {
	isRewriteSettingsArgs_Setting_Value()
}

type RewriteSettingsArgs_Setting_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_IntValue struct {
	IntValue int32 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

func (*RewriteSettingsArgs_Setting_StringValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_BoolValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_IntValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_Uint64Value) isRewriteSettingsArgs_Setting_Value() {}

type PrivilegeDelta_Grantee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrentUser bool                   `protobuf:"varint,2,opt,name=is_current_user,json=isCurrentUser,proto3" json:"is_current_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegeDelta_Grantee) Reset() {
	*x = PrivilegeDelta_Grantee{}
	mi := &file_protos_rewriter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeDelta_Grantee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeDelta_Grantee) ProtoMessage() {}

func (x *PrivilegeDelta_Grantee) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeDelta_Grantee.ProtoReflect.Descriptor instead.
func (*PrivilegeDelta_Grantee) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{11, 0}
}

func (x *PrivilegeDelta_Grantee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrivilegeDelta_Grantee) GetIsCurrentUser() bool {
	if x != nil {
		return x.IsCurrentUser
	}
	return false
}

var File_protos_rewriter_proto protoreflect.FileDescriptor

const file_protos_rewriter_proto_rawDesc = "" +
	"\n" +
	"\x15protos/rewriter.proto\x12\brewriter\"\xdb\x01\n" +
	"\x10RewriteLimitArgs\x12N\n" +
	"\rreplace_limit\x18\x02 \x01(\v2'.rewriter.RewriteLimitArgs.ReplaceLimitH\x00R\freplaceLimit\x12!\n" +
	"\vforce_limit\x18\x03 \x01(\x05H\x00R\n" +
	"forceLimit\x1aK\n" +
	"\fReplaceLimit\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x05R\tthreshold\x12\x1d\n" +
	"\n" +
	"replace_to\x18\x02 \x01(\x05R\treplaceToB\a\n" +
	"\x05value\"+\n" +
	"\x11RewriteOffsetArgs\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\"\x93\x02\n" +
	"\x1aRewriteCommonTableExprArgs\x12I\n" +
	"\acte_map\x18\x01 \x03(\v20.rewriter.RewriteCommonTableExprArgs.CteMapEntryR\x06cteMap\x1a9\n" +
	"\x0fCommonTableExpr\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x1ao\n" +
	"\vCteMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.rewriter.RewriteCommonTableExprArgs.CommonTableExprR\x05value:\x028\x01\"\xb0\x06\n" +
	"\x16RewriteTableStaticArgs\x12K\n" +
	"\ttable_map\x18\x01 \x03(\v2..rewriter.RewriteTableStaticArgs.TableMapEntryR\btableMap\x12^\n" +
	"\x10remote_table_map\x18\x02 \x03(\v24.rewriter.RewriteTableStaticArgs.RemoteTableMapEntryR\x0eremoteTableMap\x12q\n" +
	"\x17table_with_database_map\x18\x03 \x03(\v2:.rewriter.RewriteTableStaticArgs.TableWithDatabaseMapEntryR\x14tableWithDatabaseMap\x1a\x83\x01\n" +
	"\vRemoteTable\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x1aE\n" +
	"\x11TableWithDatabase\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x1a;\n" +
	"\rTableMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ao\n" +
	"\x13RemoteTableMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.rewriter.RewriteTableStaticArgs.RemoteTableR\x05value:\x028\x01\x1a{\n" +
	"\x19TableWithDatabaseMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12H\n" +
	"\x05value\x18\x02 \x01(\v22.rewriter.RewriteTableStaticArgs.TableWithDatabaseR\x05value:\x028\x01\"\xa9\b\n" +
	"\x17RewriteTableDynamicArgs\x12U\n" +
	"\fdatabase_map\x18\x01 \x03(\v22.rewriter.RewriteTableDynamicArgs.DatabaseMapEntryR\vdatabaseMap\x128\n" +
	"\x18known_physical_databases\x18\x02 \x03(\tR\x16knownPhysicalDatabases\x12N\n" +
	"$upstream_logical_database_in_context\x18\x03 \x01(\tR upstreamLogicalDatabaseInContext\x12\x14\n" +
	"\x05delim\x18\x04 \x01(\tR\x05delim\x12'\n" +
	"\x0fextra_arguments\x18\x05 \x03(\tR\x0eextraArguments\x12U\n" +
	"%upstream_physical_database_in_context\x18\x06 \x01(\tH\x00R!upstreamPhysicalDatabaseInContext\x88\x01\x01\x12\xa4\x01\n" +
	")logical_database_to_remote_upstream_index\x18\a \x03(\v2K.rewriter.RewriteTableDynamicArgs.LogicalDatabaseToRemoteUpstreamIndexEntryR$logicalDatabaseToRemoteUpstreamIndex\x12a\n" +
	"\x10remote_upstreams\x18\b \x03(\v26.rewriter.RewriteTableDynamicArgs.RemoteUpstreamsEntryR\x0fremoteUpstreams\x1a>\n" +
	"\x10DatabaseMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x0eRemoteUpstream\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x1aW\n" +
	")LogicalDatabaseToRemoteUpstreamIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1at\n" +
	"\x14RemoteUpstreamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.rewriter.RewriteTableDynamicArgs.RemoteUpstreamR\x05value:\x028\x01B(\n" +
	"&_upstream_physical_database_in_context\"\xb4\x01\n" +
	"\x14RewriteTableNameArgs\x12D\n" +
	"\fdynamic_args\x18\x01 \x01(\v2!.rewriter.RewriteTableDynamicArgsR\vdynamicArgs\x12F\n" +
	"\vstatic_args\x18\x02 \x01(\v2 .rewriter.RewriteTableStaticArgsH\x00R\n" +
	"staticArgs\x88\x01\x01B\x0e\n" +
	"\f_static_args\"\xb4\x02\n" +
	"\x13RewriteSettingsArgs\x12A\n" +
	"\bsettings\x18\x01 \x03(\v2%.rewriter.RewriteSettingsArgs.SettingR\bsettings\x1a\xd9\x01\n" +
	"\aSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.rewriter.SettingTypeR\x04type\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fuint64_value\x18\x06 \x01(\x04H\x00R\vuint64ValueB\a\n" +
	"\x05value\"\xa7\x03\n" +
	"\rRewriteOption\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.rewriter.RewriteOpR\x02op\x12H\n" +
	"\x0ftable_name_args\x18\x02 \x01(\v2\x1e.rewriter.RewriteTableNameArgsH\x00R\rtableNameArgs\x12;\n" +
	"\n" +
	"limit_args\x18\x03 \x01(\v2\x1a.rewriter.RewriteLimitArgsH\x00R\tlimitArgs\x12>\n" +
	"\voffset_args\x18\x04 \x01(\v2\x1b.rewriter.RewriteOffsetArgsH\x00R\n" +
	"offsetArgs\x12D\n" +
	"\rsettings_args\x18\x05 \x01(\v2\x1d.rewriter.RewriteSettingsArgsH\x00R\fsettingsArgs\x12[\n" +
	"\x16common_table_expr_args\x18\x06 \x01(\v2$.rewriter.RewriteCommonTableExprArgsH\x00R\x13commonTableExprArgsB\a\n" +
	"\x05value\"X\n" +
	"\x11RewriteSQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x121\n" +
	"\aoptions\x18\x02 \x03(\v2\x17.rewriter.RewriteOptionR\aoptions\"\xf2\x05\n" +
	"\x12RewriteSQLResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.rewriter.RewriteCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11sql_after_rewrite\x18\x03 \x01(\tR\x0fsqlAfterRewrite\x12>\n" +
	"\x0estatement_type\x18\x05 \x01(\x0e2\x17.rewriter.StatementTypeR\rstatementType\x12,\n" +
	"\x12failed_cte_aliases\x18\t \x03(\tR\x10failedCteAliases\x12V\n" +
	"\x0etable_rewrites\x18\n" +
	" \x03(\v2/.rewriter.RewriteSQLResponse.TableRewritesEntryR\rtableRewrites\x12_\n" +
	"\x11database_rewrites\x18\v \x03(\v22.rewriter.RewriteSQLResponse.DatabaseRewritesEntryR\x10databaseRewrites\x12Q\n" +
	"\x18original_accessed_tables\x18\f \x03(\v2\x17.rewriter.AccessedTableR\x16originalAccessedTables\x12E\n" +
	"\x11privileges_deltas\x18\r \x03(\v2\x18.rewriter.PrivilegeDeltaR\x10privilegesDeltas\x1a@\n" +
	"\x12TableRewritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15DatabaseRewritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x04\x10\x05R\x1doriginal_accessed_table_names\"\xd8\x01\n" +
	"\rAccessedTable\x12+\n" +
	"\x11original_database\x18\x01 \x01(\tR\x10originalDatabase\x12%\n" +
	"\x0eoriginal_table\x18\x02 \x01(\tR\roriginalTable\x12)\n" +
	"\x10logical_database\x18\x03 \x01(\tR\x0flogicalDatabase\x12+\n" +
	"\x11physical_database\x18\x04 \x01(\tR\x10physicalDatabase\x12\x1b\n" +
	"\tis_remote\x18\x05 \x01(\bR\bisRemote\"\xa6\x05\n" +
	"\x0ePrivilegeDelta\x127\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1f.rewriter.PrivilegeDelta.ActionR\x06action\x124\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x1e.rewriter.PrivilegeDelta.ScopeR\x05scope\x12+\n" +
	"\x11original_database\x18\x03 \x01(\tR\x10originalDatabase\x12)\n" +
	"\x10logical_database\x18\x04 \x01(\tR\x0flogicalDatabase\x12+\n" +
	"\x11physical_database\x18\x05 \x01(\tR\x10physicalDatabase\x12%\n" +
	"\x0eoriginal_table\x18\x06 \x01(\tR\roriginalTable\x12%\n" +
	"\x0ephysical_table\x18\a \x01(\tR\rphysicalTable\x12\x1e\n" +
	"\n" +
	"privileges\x18\b \x03(\tR\n" +
	"privileges\x12<\n" +
	"\bgrantees\x18\t \x03(\v2 .rewriter.PrivilegeDelta.GranteeR\bgrantees\x12!\n" +
	"\fgrant_option\x18\n" +
	" \x01(\bR\vgrantOption\x1aE\n" +
	"\aGrantee\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0fis_current_user\x18\x02 \x01(\bR\risCurrentUser\"E\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_GRANT\x10\x01\x12\x11\n" +
	"\rACTION_REVOKE\x10\x02\"C\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSCOPE_TABLE\x10\x01\x12\x12\n" +
	"\x0eSCOPE_DATABASE\x10\x02\"\x86\x01\n" +
	"\x1aRewriteErrorMessageRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x121\n" +
	"\aoptions\x18\x03 \x03(\v2\x17.rewriter.RewriteOptionR\aoptions\"\x92\x01\n" +
	"\x1bRewriteErrorMessageResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.rewriter.RewriteCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13error_after_rewrite\x18\x03 \x01(\tR\x11errorAfterRewrite*w\n" +
	"\tRewriteOp\x12\x14\n" +
	"\x10TableNameRewrite\x10\x00\x12\x10\n" +
	"\fLimitRewrite\x10\x01\x12\x11\n" +
	"\rOffsetRewrite\x10\x02\x12\x13\n" +
	"\x0fSettingsRewrite\x10\x03\x12\x1a\n" +
	"\x16CommonTableExprRewrite\x10\x04*8\n" +
	"\vSettingType\x12\n" +
	"\n" +
	"\x06String\x10\x00\x12\b\n" +
	"\x04Bool\x10\x01\x12\a\n" +
	"\x03Int\x10\x02\x12\n" +
	"\n" +
	"\x06Uint64\x10\x03*r\n" +
	"\vRewriteCode\x12\v\n" +
	"\aSuccess\x10\x00\x12\x0f\n" +
	"\vSyntaxError\x10\x01\x12\x10\n" +
	"\fRewriteError\x10\x02\x12\x18\n" +
	"\x14UnsupportedStatement\x10\x03\x12\x19\n" +
	"\x15InvalidRewriteRequest\x10\x04*\xdc\x04\n" +
	"\rStatementType\x12\x1e\n" +
	"\x1aSTATEMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STATEMENT_TYPE_SELECT\x10\x01\x12\x16\n" +
	"\x12STATEMENT_TYPE_USE\x10\x02\x12\x1e\n" +
	"\x1aSTATEMENT_TYPE_SHOW_TABLES\x10\x03\x12$\n" +
	" STATEMENT_TYPE_SHOW_CREATE_TABLE\x10\x04\x12\x1f\n" +
	"\x1bSTATEMENT_TYPE_EXISTS_TABLE\x10\x05\x12\x1f\n" +
	"\x1bSTATEMENT_TYPE_CREATE_TABLE\x10\x06\x12\x1d\n" +
	"\x19STATEMENT_TYPE_DROP_TABLE\x10\a\x12\x1e\n" +
	"\x1aSTATEMENT_TYPE_ALTER_TABLE\x10\b\x12\x1f\n" +
	"\x1bSTATEMENT_TYPE_RENAME_TABLE\x10\t\x12\x19\n" +
	"\x15STATEMENT_TYPE_INSERT\x10\n" +
	"\x12\x19\n" +
	"\x15STATEMENT_TYPE_UPDATE\x10\v\x12\x19\n" +
	"\x15STATEMENT_TYPE_DELETE\x10\f\x12\"\n" +
	"\x1eSTATEMENT_TYPE_CREATE_DATABASE\x10\r\x12!\n" +
	"\x1dSTATEMENT_TYPE_SHOW_DATABASES\x10\x0e\x12 \n" +
	"\x1cSTATEMENT_TYPE_DROP_DATABASE\x10\x0f\x12!\n" +
	"\x1dSTATEMENT_TYPE_TRUNCATE_TABLE\x10\x10\x12\x18\n" +
	"\x14STATEMENT_TYPE_GRANT\x10\x11\x12\x19\n" +
	"\x15STATEMENT_TYPE_REVOKE\x10\x122\xbf\x01\n" +
	"\x0fRewriterService\x12F\n" +
	"\aRewrite\x12\x1b.rewriter.RewriteSQLRequest\x1a\x1c.rewriter.RewriteSQLResponse\"\x00\x12d\n" +
	"\x13RewriteErrorMessage\x12$.rewriter.RewriteErrorMessageRequest\x1a%.rewriter.RewriteErrorMessageResponse\"\x00B\x1cZ\x1ahousegate/housegate/protosb\x06proto3"

var (
	file_protos_rewriter_proto_rawDescOnce sync.Once
	file_protos_rewriter_proto_rawDescData []byte
)

func file_protos_rewriter_proto_rawDescGZIP() []byte {
	file_protos_rewriter_proto_rawDescOnce.Do(func() {
		file_protos_rewriter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_rewriter_proto_rawDesc), len(file_protos_rewriter_proto_rawDesc)))
	})
	return file_protos_rewriter_proto_rawDescData
}

var file_protos_rewriter_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_protos_rewriter_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_protos_rewriter_proto_goTypes = []any{
	(RewriteOp)(0),                                     // 0: rewriter.RewriteOp
	(SettingType)(0),                                   // 1: rewriter.SettingType
	(RewriteCode)(0),                                   // 2: rewriter.RewriteCode
	(StatementType)(0),                                 // 3: rewriter.StatementType
	(PrivilegeDelta_Action)(0),                         // 4: rewriter.PrivilegeDelta.Action
	(PrivilegeDelta_Scope)(0),                          // 5: rewriter.PrivilegeDelta.Scope
	(*RewriteLimitArgs)(nil),                           // 6: rewriter.RewriteLimitArgs
	(*RewriteOffsetArgs)(nil),                          // 7: rewriter.RewriteOffsetArgs
	(*RewriteCommonTableExprArgs)(nil),                 // 8: rewriter.RewriteCommonTableExprArgs
	(*RewriteTableStaticArgs)(nil),                     // 9: rewriter.RewriteTableStaticArgs
	(*RewriteTableDynamicArgs)(nil),                    // 10: rewriter.RewriteTableDynamicArgs
	(*RewriteTableNameArgs)(nil),                       // 11: rewriter.RewriteTableNameArgs
	(*RewriteSettingsArgs)(nil),                        // 12: rewriter.RewriteSettingsArgs
	(*RewriteOption)(nil),                              // 13: rewriter.RewriteOption
	(*RewriteSQLRequest)(nil),                          // 14: rewriter.RewriteSQLRequest
	(*RewriteSQLResponse)(nil),                         // 15: rewriter.RewriteSQLResponse
	(*AccessedTable)(nil),                              // 16: rewriter.AccessedTable
	(*PrivilegeDelta)(nil),                             // 17: rewriter.PrivilegeDelta
	(*RewriteErrorMessageRequest)(nil),                 // 18: rewriter.RewriteErrorMessageRequest
	(*RewriteErrorMessageResponse)(nil),                // 19: rewriter.RewriteErrorMessageResponse
	(*RewriteLimitArgs_ReplaceLimit)(nil),              // 20: rewriter.RewriteLimitArgs.ReplaceLimit
	(*RewriteCommonTableExprArgs_CommonTableExpr)(nil), // 21: rewriter.RewriteCommonTableExprArgs.CommonTableExpr
	nil, // 22: rewriter.RewriteCommonTableExprArgs.CteMapEntry
	(*RewriteTableStaticArgs_RemoteTable)(nil),       // 23: rewriter.RewriteTableStaticArgs.RemoteTable
	(*RewriteTableStaticArgs_TableWithDatabase)(nil), // 24: rewriter.RewriteTableStaticArgs.TableWithDatabase
	nil, // 25: rewriter.RewriteTableStaticArgs.TableMapEntry
	nil, // 26: rewriter.RewriteTableStaticArgs.RemoteTableMapEntry
	nil, // 27: rewriter.RewriteTableStaticArgs.TableWithDatabaseMapEntry
	nil, // 28: rewriter.RewriteTableDynamicArgs.DatabaseMapEntry
	(*RewriteTableDynamicArgs_RemoteUpstream)(nil), // 29: rewriter.RewriteTableDynamicArgs.RemoteUpstream
	nil,                                 // 30: rewriter.RewriteTableDynamicArgs.LogicalDatabaseToRemoteUpstreamIndexEntry
	nil,                                 // 31: rewriter.RewriteTableDynamicArgs.RemoteUpstreamsEntry
	(*RewriteSettingsArgs_Setting)(nil), // 32: rewriter.RewriteSettingsArgs.Setting
	nil,                                 // 33: rewriter.RewriteSQLResponse.TableRewritesEntry
	nil,                                 // 34: rewriter.RewriteSQLResponse.DatabaseRewritesEntry
	(*PrivilegeDelta_Grantee)(nil),      // 35: rewriter.PrivilegeDelta.Grantee
}
var file_protos_rewriter_proto_depIdxs = []int32{
	20, // 0: rewriter.RewriteLimitArgs.replace_limit:type_name -> rewriter.RewriteLimitArgs.ReplaceLimit
	22, // 1: rewriter.RewriteCommonTableExprArgs.cte_map:type_name -> rewriter.RewriteCommonTableExprArgs.CteMapEntry
	25, // 2: rewriter.RewriteTableStaticArgs.table_map:type_name -> rewriter.RewriteTableStaticArgs.TableMapEntry
	26, // 3: rewriter.RewriteTableStaticArgs.remote_table_map:type_name -> rewriter.RewriteTableStaticArgs.RemoteTableMapEntry
	27, // 4: rewriter.RewriteTableStaticArgs.table_with_database_map:type_name -> rewriter.RewriteTableStaticArgs.TableWithDatabaseMapEntry
	28, // 5: rewriter.RewriteTableDynamicArgs.database_map:type_name -> rewriter.RewriteTableDynamicArgs.DatabaseMapEntry
	30, // 6: rewriter.RewriteTableDynamicArgs.logical_database_to_remote_upstream_index:type_name -> rewriter.RewriteTableDynamicArgs.LogicalDatabaseToRemoteUpstreamIndexEntry
	31, // 7: rewriter.RewriteTableDynamicArgs.remote_upstreams:type_name -> rewriter.RewriteTableDynamicArgs.RemoteUpstreamsEntry
	10, // 8: rewriter.RewriteTableNameArgs.dynamic_args:type_name -> rewriter.RewriteTableDynamicArgs
	9,  // 9: rewriter.RewriteTableNameArgs.static_args:type_name -> rewriter.RewriteTableStaticArgs
	32, // 10: rewriter.RewriteSettingsArgs.settings:type_name -> rewriter.RewriteSettingsArgs.Setting
	0,  // 11: rewriter.RewriteOption.op:type_name -> rewriter.RewriteOp
	11, // 12: rewriter.RewriteOption.table_name_args:type_name -> rewriter.RewriteTableNameArgs
	6,  // 13: rewriter.RewriteOption.limit_args:type_name -> rewriter.RewriteLimitArgs
	7,  // 14: rewriter.RewriteOption.offset_args:type_name -> rewriter.RewriteOffsetArgs
	12, // 15: rewriter.RewriteOption.settings_args:type_name -> rewriter.RewriteSettingsArgs
	8,  // 16: rewriter.RewriteOption.common_table_expr_args:type_name -> rewriter.RewriteCommonTableExprArgs
	13, // 17: rewriter.RewriteSQLRequest.options:type_name -> rewriter.RewriteOption
	2,  // 18: rewriter.RewriteSQLResponse.code:type_name -> rewriter.RewriteCode
	3,  // 19: rewriter.RewriteSQLResponse.statement_type:type_name -> rewriter.StatementType
	33, // 20: rewriter.RewriteSQLResponse.table_rewrites:type_name -> rewriter.RewriteSQLResponse.TableRewritesEntry
	34, // 21: rewriter.RewriteSQLResponse.database_rewrites:type_name -> rewriter.RewriteSQLResponse.DatabaseRewritesEntry
	16, // 22: rewriter.RewriteSQLResponse.original_accessed_tables:type_name -> rewriter.AccessedTable
	17, // 23: rewriter.RewriteSQLResponse.privileges_deltas:type_name -> rewriter.PrivilegeDelta
	4,  // 24: rewriter.PrivilegeDelta.action:type_name -> rewriter.PrivilegeDelta.Action
	5,  // 25: rewriter.PrivilegeDelta.scope:type_name -> rewriter.PrivilegeDelta.Scope
	35, // 26: rewriter.PrivilegeDelta.grantees:type_name -> rewriter.PrivilegeDelta.Grantee
	13, // 27: rewriter.RewriteErrorMessageRequest.options:type_name -> rewriter.RewriteOption
	2,  // 28: rewriter.RewriteErrorMessageResponse.code:type_name -> rewriter.RewriteCode
	21, // 29: rewriter.RewriteCommonTableExprArgs.CteMapEntry.value:type_name -> rewriter.RewriteCommonTableExprArgs.CommonTableExpr
	23, // 30: rewriter.RewriteTableStaticArgs.RemoteTableMapEntry.value:type_name -> rewriter.RewriteTableStaticArgs.RemoteTable
	24, // 31: rewriter.RewriteTableStaticArgs.TableWithDatabaseMapEntry.value:type_name -> rewriter.RewriteTableStaticArgs.TableWithDatabase
	29, // 32: rewriter.RewriteTableDynamicArgs.RemoteUpstreamsEntry.value:type_name -> rewriter.RewriteTableDynamicArgs.RemoteUpstream
	1,  // 33: rewriter.RewriteSettingsArgs.Setting.type:type_name -> rewriter.SettingType
	14, // 34: rewriter.RewriterService.Rewrite:input_type -> rewriter.RewriteSQLRequest
	18, // 35: rewriter.RewriterService.RewriteErrorMessage:input_type -> rewriter.RewriteErrorMessageRequest
	15, // 36: rewriter.RewriterService.Rewrite:output_type -> rewriter.RewriteSQLResponse
	19, // 37: rewriter.RewriterService.RewriteErrorMessage:output_type -> rewriter.RewriteErrorMessageResponse
	36, // [36:38] is the sub-list for method output_type
	34, // [34:36] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_protos_rewriter_proto_init() }
func file_protos_rewriter_proto_init() {
	if File_protos_rewriter_proto != nil {
		return
	}
	file_protos_rewriter_proto_msgTypes[0].OneofWrappers = []any{
		(*RewriteLimitArgs_ReplaceLimit_)(nil),
		(*RewriteLimitArgs_ForceLimit)(nil),
	}
	file_protos_rewriter_proto_msgTypes[4].OneofWrappers = []any{}
	file_protos_rewriter_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_rewriter_proto_msgTypes[7].OneofWrappers = []any{
		(*RewriteOption_TableNameArgs)(nil),
		(*RewriteOption_LimitArgs)(nil),
		(*RewriteOption_OffsetArgs)(nil),
		(*RewriteOption_SettingsArgs)(nil),
		(*RewriteOption_CommonTableExprArgs)(nil),
	}
	file_protos_rewriter_proto_msgTypes[26].OneofWrappers = []any{
		(*RewriteSettingsArgs_Setting_StringValue)(nil),
		(*RewriteSettingsArgs_Setting_BoolValue)(nil),
		(*RewriteSettingsArgs_Setting_IntValue)(nil),
		(*RewriteSettingsArgs_Setting_Uint64Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_rewriter_proto_rawDesc), len(file_protos_rewriter_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_rewriter_proto_goTypes,
		DependencyIndexes: file_protos_rewriter_proto_depIdxs,
		EnumInfos:         file_protos_rewriter_proto_enumTypes,
		MessageInfos:      file_protos_rewriter_proto_msgTypes,
	}.Build()
	File_protos_rewriter_proto = out.File
	file_protos_rewriter_proto_goTypes = nil
	file_protos_rewriter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RewriterServiceClient is the client API for RewriterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RewriterServiceClient interface {
	Rewrite(ctx context.Context, in *RewriteSQLRequest, opts ...grpc.CallOption) (*RewriteSQLResponse, error)
	RewriteErrorMessage(ctx context.Context, in *RewriteErrorMessageRequest, opts ...grpc.CallOption) (*RewriteErrorMessageResponse, error)
}

type rewriterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRewriterServiceClient(cc grpc.ClientConnInterface) RewriterServiceClient {
	return &rewriterServiceClient{cc}
}

func (c *rewriterServiceClient) Rewrite(ctx context.Context, in *RewriteSQLRequest, opts ...grpc.CallOption) (*RewriteSQLResponse, error) {
	out := new(RewriteSQLResponse)
	err := c.cc.Invoke(ctx, "/rewriter.RewriterService/Rewrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rewriterServiceClient) RewriteErrorMessage(ctx context.Context, in *RewriteErrorMessageRequest, opts ...grpc.CallOption) (*RewriteErrorMessageResponse, error) {
	out := new(RewriteErrorMessageResponse)
	err := c.cc.Invoke(ctx, "/rewriter.RewriterService/RewriteErrorMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RewriterServiceServer is the server API for RewriterService service.
type RewriterServiceServer interface {
	Rewrite(context.Context, *RewriteSQLRequest) (*RewriteSQLResponse, error)
	RewriteErrorMessage(context.Context, *RewriteErrorMessageRequest) (*RewriteErrorMessageResponse, error)
}

// UnimplementedRewriterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRewriterServiceServer struct {
}

func (*UnimplementedRewriterServiceServer) Rewrite(context.Context, *RewriteSQLRequest) (*RewriteSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewrite not implemented")
}
func (*UnimplementedRewriterServiceServer) RewriteErrorMessage(context.Context, *RewriteErrorMessageRequest) (*RewriteErrorMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewriteErrorMessage not implemented")
}

func RegisterRewriterServiceServer(s *grpc.Server, srv RewriterServiceServer) {
	s.RegisterService(&_RewriterService_serviceDesc, srv)
}

func _RewriterService_Rewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewriteSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewriterServiceServer).Rewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rewriter.RewriterService/Rewrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewriterServiceServer).Rewrite(ctx, req.(*RewriteSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RewriterService_RewriteErrorMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewriteErrorMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewriterServiceServer).RewriteErrorMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rewriter.RewriterService/RewriteErrorMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewriterServiceServer).RewriteErrorMessage(ctx, req.(*RewriteErrorMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RewriterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rewriter.RewriterService",
	HandlerType: (*RewriterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rewrite",
			Handler:    _RewriterService_Rewrite_Handler,
		},
		{
			MethodName: "RewriteErrorMessage",
			Handler:    _RewriterService_RewriteErrorMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/rewriter.proto",
}
