load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "indexing_usage",
    srcs = [
        "config.go",
        "plugin.go",
    ],
    importpath = "github.com/housegate/housegate/pkg/plugins/indexing_usage",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/billing",
        "//pkg/log",
        "//pkg/plugin",
        "//pkg/sqlmeta",
    ],
)

go_test(
    name = "indexing_usage_test",
    srcs = ["plugin_test.go"],
    embed = [":indexing_usage"],
    deps = [
        "//pkg/billing",
        "//pkg/chproto",
        "//pkg/chsession",
        "//pkg/plugin",
        "//pkg/sqlmeta",
    ],
)
