load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "auth",
    srcs = [
        "eth_validator.go",
        "jws.go",
        "relay_signer.go",
        "signer.go",
        "types.go",
    ],
    importpath = "github.com/housegate/housegate/pkg/auth",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/log",
        "@com_github_ethereum_go_ethereum//crypto",
        "@org_golang_x_crypto//sha3",
    ],
)

go_test(
    name = "auth_test",
    srcs = [
        "eth_validator_test.go",
        "peer_signer_test.go",
        "relay_signer_test.go",
        "statement_v2_test.go",
    ],
    embed = [":auth"],
    deps = ["@com_github_ethereum_go_ethereum//crypto"],
)
