load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "housegate_lib",
    srcs = [
        "console_handler.go",
        "main.go",
        "secret.go",
    ],
    data = [
        "//configs:exported_configs_example",
    ],
    importpath = "housegate/housegate/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//:housegate",
        "//pkg/config",
        "//pkg/log",
        "//pkg/secretsload",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
    ],
)

go_binary(
    name = "housegate",
    embed = [":housegate_lib"],
    visibility = ["//visibility:public"],
)
