load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sqlident",
    srcs = ["ident.go"],
    importpath = "housegate/housegate/pkg/sqlident",
    visibility = ["//visibility:public"],
)

go_test(
    name = "sqlident_test",
    srcs = ["ident_test.go"],
    embed = [":sqlident"],
)
