load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "credentials",
    srcs = [
        "ckhmanager.go",
        "types.go",
    ],
    importpath = "housegate/housegate/pkg/credentials",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/log",
        "//pkg/secretsload",
        "@in_yaml_go_yaml_v3//:yaml",
    ],
)

go_test(
    name = "credentials_test",
    srcs = ["ckhmanager_test.go"],
    embed = [":credentials"],
)
