load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rewriter",
    srcs = [
        "aliases.go",
        "args.go",
        "sentio.go",
        "types.go",
    ],
    importpath = "housegate/housegate/pkg/rewriter",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cluster",
        "//pkg/credentials",
        "//pkg/log",
        "//pkg/network",
        "//pkg/peer",
        "//pkg/registry",
        "//pkg/route",
        "//pkg/sqlmeta",
        "@com_github_housegate_rewriter_go//gen/pb",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//keepalive",
    ],
)

go_test(
    name = "rewriter_test",
    srcs = ["sentio_test.go"],
    embed = [":rewriter"],
    deps = [
        "//pkg/network",
        "//pkg/registry",
    ],
)
