load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "credential",
    srcs = ["injector.go"],
    importpath = "housegate/housegate/pkg/plugins/credential",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/auth",
        "//pkg/chproto",
        "//pkg/chsession",
        "//pkg/credentials",
        "//pkg/log",
        "//pkg/peer",
        "//pkg/plugin",
    ],
)

go_test(
    name = "credential_test",
    srcs = ["injector_test.go"],
    embed = [":credential"],
    deps = [
        "//pkg/auth",
        "//pkg/chproto",
        "//pkg/chsession",
        "//pkg/peer",
    ],
)
