load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "route",
    srcs = [
        "route.go",
        "signer.go",
        "stripper.go",
    ],
    importpath = "housegate/housegate/pkg/plugins/route",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/auth",
        "//pkg/chproto",
        "//pkg/chsession",
        "//pkg/log",
        "//pkg/plugin",
        "//pkg/route",
    ],
)

go_test(
    name = "route_test",
    srcs = [
        "signer_test.go",
        "stripper_test.go",
    ],
    embed = [":route"],
    deps = [
        "//pkg/auth",
        "//pkg/chproto",
        "//pkg/chsession",
        "//pkg/peer",
        "//pkg/plugin",
        "//pkg/route",
    ],
)
