load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cluster",
    srcs = [
        "cluster_iface.go",
        "health.go",
        "manager.go",
        "pool.go",
        "router.go",
        "types.go",
    ],
    importpath = "housegate/housegate/pkg/cluster",
    visibility = ["//visibility:public"],
    deps = [
        "@sentio-core//common/log",
    ],
)
